# Generated by Django 2.2.2 on 2019-06-16 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('id_number', models.CharField(default='', max_length=255)),
                ('picture', models.ImageField(blank=True, default='', max_length=255, upload_to='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tableros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, default='', max_length=255)),
                ('table_privacy', models.IntegerField()),
                ('table_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuarios')),
            ],
            options={
                'ordering': ('table_name',),
            },
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.CharField(default='', max_length=1000)),
                ('table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Tableros')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuarios')),
            ],
            options={
                'ordering': ('thing',),
            },
        ),
    ]
